-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 15:37:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `BrandId` VARCHAR(10) NOT NULL,
  `BrandName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BrandId`),
  UNIQUE INDEX `BrandName_UNIQUE` (`BrandName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `ProdId` VARCHAR(10) NOT NULL,
  `ProdName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `Price` DOUBLE(8,2) NOT NULL,
  `Brand_BrandId` VARCHAR(10) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProdId`, `Brand_BrandId`),
  UNIQUE INDEX `ProdName_UNIQUE` (`ProdName` ASC) VISIBLE,
  INDEX `fk_Product_Brand1_idx` (`Brand_BrandId` ASC) VISIBLE,
  UNIQUE INDEX `Image_UNIQUE` (`Image` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_BrandId`)
    REFERENCES `mydb`.`Brand` (`BrandId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `ColorId` VARCHAR(10) NOT NULL,
  `ColorName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ColorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_has_Color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Color` (
  `Product_ProdId` VARCHAR(10) NOT NULL,
  `Color_ColorId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Product_ProdId`, `Color_ColorId`),
  INDEX `fk_Product_has_Color_Color1_idx` (`Color_ColorId` ASC) VISIBLE,
  INDEX `fk_Product_has_Color_Product_idx` (`Product_ProdId` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Color_Product`
    FOREIGN KEY (`Product_ProdId`)
    REFERENCES `mydb`.`Product` (`ProdId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Color_Color1`
    FOREIGN KEY (`Color_ColorId`)
    REFERENCES `mydb`.`Color` (`ColorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
